In [1]:
import numpy as np


In [2]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Conv2D,MaxPooling2D,Flatten,BatchNormalization,Dropout


In [3]:
import pandas as pd


In [4]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [5]:
tf.config.run_functions_eagerly(True)

In [6]:
test_data=pd.read_csv('/content/gdrive/MyDrive/test.csv')

In [7]:
df=pd.read_csv('/content/gdrive/MyDrive/train.csv')

In [8]:
df.shape


(5250, 1201)

In [9]:
X=df.drop(columns=['labels'])

In [10]:
X

f_0       f_1       f_2       f_3       f_4       f_5       f_6  \
0    -2.033875  0.978446 -0.142131 -0.177117 -1.470684  1.669562 -0.196530   
1    -0.348835  0.294815 -0.557577 -2.020773 -1.234715  1.633930 -1.680658   
2     0.113248 -0.607726 -0.947791  0.830851  0.998291  0.498321 -1.493958   
3     1.223321 -0.479048 -1.925789  1.680377  0.021840 -1.453307  0.605559   
4     0.160109  0.422684 -0.308029  0.227744  0.432854  0.608348  0.193832   
...        ...       ...       ...       ...       ...       ...       ...   
5245  1.157565 -0.142219  1.043992  1.144946  1.195423  0.248978 -1.505100   
5246  1.424709  0.235910  1.356778  1.368099 -0.318862  1.039765 -0.986854   
5247 -0.375687  1.524455  0.012514 -0.007917  0.073809 -0.906909 -1.254247   
5248 -0.478238  1.666142  0.049609 -0.428752 -0.362771  1.798104 -0.214314   
5249 -0.750874  0.267008 -0.155041 -0.179867 -0.155041 -0.303999 -0.279173   

           f_7       f_8       f_9  ...    f_1190    f_1191    f_1192  \
0    -0.125239 -0.452284 -0.128052  ... -1.111266  0.716084  0.060039   
1    -0.358146  0.166122 -1.656990  ...  0.735240  0.829781  1.521941   
2     0.789572 -1.311018  0.848524  ...  0.104698  0.616189 -1.035953   
3    -0.019024  1.065448  0.717341  ...  0.360237 -1.957863 -0.123384   
4     1.035091 -0.538868  0.778445  ...  0.416629  1.441766  0.212572   
...        ...       ...       ...  ...       ...       ...       ...   
5245 -0.874137 -1.782724  0.261597  ...  1.195423 -0.255793 -0.154838   
5246 -0.330184 -1.383120  1.243559  ...  1.424709 -1.066107  0.881258   
5247  1.606182  0.298557  0.053378  ... -0.028349 -0.968204 -1.233815   
5248  0.775400 -0.379267  0.725914  ... -0.428752 -1.121552 -0.379267   
5249  1.731765  0.564925  1.508328  ... -0.303999 -0.850180  0.937321   

        f_1193    f_1194    f_1195    f_1196    f_1197    f_1198    f_1199  
0     0.301279 -1.174846 -1.076498 -0.069452 -0.604012 -2.179176  0.558003  
1     1.347946  0.754505  1.330642 -0.754453  0.582956  0.252671  1.495870  
2     2.111387 -0.984415  1.148076 -1.433554  0.243372  0.170083  1.274795  
3     1.505329  0.660290 -1.769443 -0.547756 -0.568122  0.244645  0.982116  
4    -0.994721  1.143999 -2.166923 -1.199248 -1.028636  0.752791  0.317169  
...        ...       ...       ...       ...       ...       ...       ...  
5245  0.413029 -0.482939 -1.277953 -0.445082  1.195423 -0.924614 -0.432462  
5246 -0.488691 -1.281223 -1.213291  0.122692  1.175627 -1.145360  0.451026  
5247  1.626613 -0.191802  1.115823  0.380284 -0.293960  0.135104  1.381434  
5248 -0.593705  0.049609  1.765114  0.313533 -0.329781 -1.220524  0.033114  
5249 -1.594972  1.036626  1.582807  1.036626 -0.254346  0.664230  1.831071  

[5250 rows x 1200 columns]

In [11]:
X.shape

(5250, 1200)

In [12]:
X_=X.to_numpy()

In [13]:
X_

array([[-2.03387548,  0.97844593, -0.14213084, ..., -0.60401202,
        -2.17917563,  0.55800316],
       [-0.34883507,  0.29481456, -0.55757667, ...,  0.58295645,
         0.25267098,  1.49586981],
       [ 0.1132478 , -0.60772569, -0.94779103, ...,  0.24337245,
         0.17008343,  1.27479505],
       ...,
       [-0.37568664,  1.52445515,  0.01251437, ..., -0.29396011,
         0.13510417,  1.38143372],
       [-0.47823807,  1.66614235,  0.04960942, ..., -0.32978097,
        -1.2205236 ,  0.03311418],
       [-0.75087434,  0.26700789, -0.15504084, ..., -0.25434642,
         0.66423022,  1.83107082]])

In [14]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(X_)

array([[-2.60426628,  0.99197232, -0.47376538, ..., -1.03381538,
        -2.00978998,  0.6148496 ],
       [-0.79041827,  0.23144671, -0.90237498, ...,  0.22311512,
         0.48813418,  1.66050162],
       [-0.29301293, -0.77261046, -1.30495363, ..., -0.13648457,
         0.40330259,  1.41401959],
       ...,
       [-0.81932242,  1.59939616, -0.31422009, ..., -0.70548846,
         0.36737287,  1.53291384],
       [-0.92971308,  1.75702021, -0.27594966, ..., -0.74342066,
        -1.02508969,  0.02963718],
       [-1.22319016,  0.20051236, -0.48708444, ..., -0.66353987,
         0.9108762 ,  2.03422597]])

In [15]:
type(X_)

numpy.ndarray

In [16]:
X.isna().sum()

f_0       0
f_1       0
f_2       0
f_3       0
f_4       0
         ..
f_1195    0
f_1196    0
f_1197    0
f_1198    0
f_1199    0
Length: 1200, dtype: int64

In [17]:
# create ANN model

model = Sequential()

model.add(Dense(128,activation='relu',kernel_initializer='he_normal',input_shape=(1200,)))
model.add(Dropout(0.5))
model.add(BatchNormalization())

model.add(Dense(64,activation='relu',kernel_initializer='he_normal'))
model.add(Dropout(0.5))
model.add(BatchNormalization())

model.add(Dense(32,activation='relu'))
model.add(Dropout(0.5))
model.add(BatchNormalization())

model.add(Dense(1,activation='sigmoid'))


In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 128)               153728    
                                                                 
 dropout (Dropout)           (None, 128)               0         
                                                                 
 batch_normalization (BatchN  (None, 128)              512       
 ormalization)                                                   
                                                                 
 dense_1 (Dense)             (None, 64)                8256      
                                                                 
 dropout_1 (Dropout)         (None, 64)                0         
                                                                 
 batch_normalization_1 (Batc  (None, 64)               256       
 hNormalization)                                        

In [19]:
X_.shape

(5250, 1200)

In [20]:
Y=df['labels']

In [21]:
 from sklearn.model_selection import train_test_split


In [22]:
X_train, X_val, y_train, y_val = train_test_split(X_, Y, test_size=0.2, random_state=42)

In [23]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [24]:
history = model.fit(X_train,y_train,epochs=10,validation_data=(X_val,y_val))

/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/structured_function.py:254: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(


Epoch 1/10
132/132 [==============================] - 16s 95ms/step - loss: 0.6774 - accuracy: 0.6438 - val_loss: 0.3741 - val_accuracy: 0.8486
Epoch 2/10
132/132 [==============================] - 12s 94ms/step - loss: 0.4969 - accuracy: 0.7579 - val_loss: 0.3301 - val_accuracy: 0.8600
Epoch 3/10
132/132 [==============================] - 13s 96ms/step - loss: 0.4237 - accuracy: 0.8038 - val_loss: 0.3198 - val_accuracy: 0.8638
Epoch 4/10
132/132 [==============================] - 12s 92ms/step - loss: 0.3817 - accuracy: 0.8274 - val_loss: 0.3166 - val_accuracy: 0.8648
Epoch 5/10
132/132 [==============================] - 13s 99ms/step - loss: 0.3639 - accuracy: 0.8390 - val_loss: 0.3173 - val_accuracy: 0.8676
Epoch 6/10
132/132 [==============================] - 13s 96ms/step - loss: 0.3314 - accuracy: 0.8538 - val_loss: 0.3173 - val_accuracy: 0.8657
Epoch 7/10
132/132 [==============================] - 12s 92ms/step - loss: 0.3037 - accuracy: 0.8671 - val_loss: 0.3163 - val_accuracy:

In [32]:
test_data=pd.read_csv('/content/gdrive/MyDrive/test.csv')

In [33]:
ids=test_data['id']

In [34]:
test_data=test_data.drop(columns=['id'])

In [35]:
test_data=test_data.to_numpy()

In [36]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
scaler.fit_transform(test_data)

array([[-3.99766283,  0.90850621, -0.86053999, ..., -0.84374006,
        -0.32079492, -1.92542557],
       [-0.94547318,  1.00570603,  0.66536668, ...,  1.70674983,
         0.90760882, -0.50419365],
       [ 0.77024325, -0.71683975,  2.34062452, ..., -1.00257203,
        -0.66977485,  1.21399921],
       ...,
       [ 0.90084345,  1.3191385 , -0.23422056, ...,  0.89065631,
        -1.23610518,  1.56326275],
       [ 0.67972755, -0.24436042,  0.74884119, ...,  0.71912829,
        -1.25167718,  0.50212592],
       [-1.8138962 , -0.65583759, -0.50604008, ...,  0.06211087,
         0.15354715, -0.66619123]])

In [37]:
Y_pred=model.predict(test_data)

13/71 [====>.........................] - ETA: 0s

/usr/local/lib/python3.10/dist-packages/tensorflow/python/data/ops/structured_function.py:254: UserWarning: Even though the `tf.config.experimental_run_functions_eagerly` option is set, this option does not apply to tf.data functions. To force eager execution of tf.data functions, please use `tf.data.experimental.enable_debug_mode()`.
  warnings.warn(


71/71 [==============================] - 1s 10ms/step


In [38]:
def my_function(x):
  return 1 if x>0.5 else 0

In [39]:
Y_pred = np.array([my_function(xi) for xi in Y_pred])

In [40]:
Y_pred


array([1, 0, 0, ..., 1, 0, 1])

In [41]:
Y_pred=Y_pred.reshape(2250,1)

In [42]:
ids

0          1
1          2
2          3
3          4
4          5
        ... 
2245    2246
2246    2247
2247    2248
2248    2249
2249    2250
Name: id, Length: 2250, dtype: int64

In [43]:
labels = pd.DataFrame(Y_pred, columns = ['labels'])

In [44]:
ids=pd.concat([ids,labels],axis=1,join='inner')

In [45]:
ids

id  labels
0        1       1
1        2       0
2        3       0
3        4       0
4        5       0
...    ...     ...
2245  2246       0
2246  2247       0
2247  2248       1
2248  2249       0
2249  2250       1

[2250 rows x 2 columns]

In [47]:
ids.to_csv('ann2.csv',index=False)